#
# Copyright 2017 HyperHQ Inc.
#
# SPDX-License-Identifier: Apache-2.0
#


os:
  - linux
  - osx
  - linux-ppc64le

matrix:
  include:
    - os: linux
      sudo: required
      dist: xenial
  allow_failures:
    - os: osx

language: go
go:
  - 1.13.9

go_import_path: github.com/kata-containers/shim

env:
  - target_branch=$TRAVIS_BRANCH

before_script:
  - ".ci/static-checks.sh"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq              ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y -qq automake moreutils ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install bash; fi

install:
  - cd ${TRAVIS_BUILD_DIR} && make

script:
  - cd ${TRAVIS_BUILD_DIR} && make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
